cat > _config.yml << 'EOF'
title: "Fanha"
description: "Blog tentang privacy, digital minimalism, dan produk digital"
baseurl: ""
url: "https://fanha.github.io"

permalink: /blog/:title/
theme: minima
EOF
